const { resolve } = require('path');
const { writeFileSync, mkdirSync } = require('fs');
const dotenv = require('dotenv');

const root = process.cwd();
const envFile = resolve(root, '.env');
const defaults = {
  NG_APP_API_URL: 'http://localhost:8081/api',
  NG_APP_PRODUCTION: 'false'
};

dotenv.config({ path: envFile });

const apiUrl = process.env.NG_APP_API_URL || defaults.NG_APP_API_URL;
const production = (process.env.NG_APP_PRODUCTION || defaults.NG_APP_PRODUCTION).toLowerCase() === 'true';

const targetPath = resolve(root, 'src/environments/environment.generated.ts');
const fileContents = `// This file is automatically generated by scripts/generate-env.cjs
// Do not edit manually. Update values in .env instead.

export const generatedEnvironment = {
  production: ${production},
  apiUrl: '${apiUrl.replace(/'/g, "\\'")}'
};
`;

mkdirSync(resolve(root, 'src/environments'), { recursive: true });
writeFileSync(targetPath, fileContents, { encoding: 'utf-8' });
